sudo: false

language: cpp

env:
  global:
    - PATH=$HOME/cache/bin/:$PATH
    
matrix:
    include:
        # minimum supported compiler on OS X
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: BUILD_CONFIGURATION=0 MACOSX_DEPLOYMENT_TARGET=10.10
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: BUILD_CONFIGURATION=1 MACOSX_DEPLOYMENT_TARGET=10.10

cache:
  directories:
    - $HOME/cache

branches:
  except:
    - gh_pages

script:
  - ctest -VV -S ./cmake/usCTestScript_travis.cmake
  #- for i in {1..10}; do /tmp/us/bin/usFrameworkTestDriver FrameworkTest; done
  #- cd /tmp/us && ctest -R FrameworkTest --repeat-until-fail 10
  #- ls /tmp/us/bin
  #- ls .

