sudo: false

language: cpp

env:
  global:
    - PATH=$HOME/cache/bin/:$PATH
    
matrix:
    include:
        # minimum supported compiler on OS X
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: BUILD_CONFIGURATION=0 MACOSX_DEPLOYMENT_TARGET=10.10 RUN_VIA_CTEST=0
        - os: osx
          osx_image: xcode6.4
          compiler: clang
          env: BUILD_CONFIGURATION=1 MACOSX_DEPLOYMENT_TARGET=10.10 RUN_VIA_CTEST=0

cache:
  directories:
    - $HOME/cache

branches:
  except:
    - gh_pages

script:
  - vm_stat
  - ctest -VV -S ./cmake/usCTestScript_travis.cmake
  #- for i in {1..10}; do /tmp/us/bin/usFrameworkTestDriver FrameworkTest; done
  - vm_stat
  - if [[ "$RUN_VIA_CTEST" == "0" ]]; then for test in AnyTest BundleRegistryPerformanceTest FrameworkEventTest FrameworkListenerTest FrameworkTest FrameworkFactoryTest HelgrindTest LDAPFilterTest LDAPQueryTest LogTest BundleEventTest BundleHooksTest BundleManifestTest BundleTest BundleResourceTest MemcheckTest ServiceFactoryTest ServiceHooksTest ServiceRegistryPerformanceTest ServiceRegistryTest ServiceTemplateTest ServiceTrackerTest StaticBundleResourceTest StaticBundleTest ServiceListenerTest SharedLibraryTest ConcurrencyTest ; do /tmp/us/bin/usFrameworkTestDriver $test; done; fi
  - ls /tmp/us/bin
  #- ls .
  - vm_stat

